### PR TITLE
fix: update interface path and ESLint.

### PR DESCRIPTION
**Pull request by downdawn**

### CODE REVIEW

**Comment by downdawn** [comment]
please review.

**Comment by wu-clan** [comment]
Hi, @downdawn 

My local execution of eslint seems to format all the files.

IDE: WebStorm

image

**Review by wu-clan — APPROVED** [review]

**Comment by downdawn** [comment]
I also use WebStorm.

In theory, if the .eslintrc.js configuration is the same, it shouldn't change.

**Comment by wu-clan** [comment]
I will merge it and pull it again.

**Pull request merged**
