### PR TITLE
feat: clean up redundant code and fix

### LINKED ISSUE #28: Code cleanup
Code cleanup records.

Includes, but is not limited to, the following:

- [x] Browser page header
- [x] Login page title
- [x] Footer content
- [x] mock data page
- [x] redundant menu
- [x] redundant code

### PR DESCRIPTION
**Pull request by wu-clan**
WIP

### CODE REVIEW

**Comment by wu-clan** [comment]
PLR.

**Review by downdawn — APPROVED** [review]

**Comment by downdawn** [comment]
LGTM.

**Comment by downdawn** [comment]
There is a question, will you not consider switching between Chinese and English in the future? 
Now the route name on the left is Chinese passed in the background.

**Comment by wu-clan** [comment]
Are you mean the menu?

The four known fields I wrote directly in the file in Chinese, the later realization of the corresponding function is to change them

**Pull request merged**
